# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 00:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='investor_info',
            new_name='investor_info_table',
        ),
        migrations.RenameModel(
            old_name='seek_info',
            new_name='seek_info_table',
        ),
    ]
