# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_refer_info_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seek_info_table',
            old_name='refer_name',
            new_name='question',
        ),
    ]
